# Travis CI
language: ruby
rvm:
- 2.0
- 2.1
install: "travis_retry script/unbundle ; travis_retry script/bootstrap"
before_script:
  - chmod a+x script/benchmark
  - chmod a+x script/bootstrap
script: script/benchmark
notifications:
  irc:
    on_success: change
    on_failure: change
    channels:
    - irc.freenode.org#bunto
    template:
    - '%{repository}#%{build_number} %{message} %{build_url}'
  email:
    on_success: never
    on_failure: change
